### ISSUE TITLE
7.5" bwr: showFont() sometimes prints garbage depending on stuff done before

### ISSUE THREAD

**Issue by teo1978** [ZinggJM/GxEPD2_32#1]
I know, support for 7.5" bwr is experimental and I know, you don't have a display to test on, but I'll report the issue anyway.

I tested the example "GxEPD2_32_Experimental_7_5_bwr" on a WaveShare 7.5-inch b/w/r display
https://www.waveshare.com/7.5inch-e-paper-hat-b.htm
and an ESP8266
https://learn.sparkfun.com/tutorials/esp8266-thing-development-board-hookup-guide/all

When running the example as is, helloWorld(), helloArduino() and helloEpaper() seem to work as expected, but when **showFont() is called**, the output is some garbage mixed with the preexisting image:

![image](https://user-images.githubusercontent.com/542107/37867411-46dbd862-2f98-11e8-8dfe-ba3a15aea915.png)

If I modify the setup() method **removing everything before and after showFont()**, then the output is as **expected** (displays some text, including the name of the font, several characters in black and a few characters in red).

If I leave setup() like this:
```
void setup()
{
  Serial.begin(115200);
  Serial.println();
  Serial.println("setup");
  display.init();
  helloWorld(); // calling helloWorld() but not helloArduino() or helloEpaper()
  delay(1000);
  
  showFont("FreeMonoBold9pt7b", &FreeMonoBold9pt7b);
  delay(1000);
  
  Serial.println("setup done");
}
```
then it **also works as expected**.

**Comment by teo1978** [comment]
I suspect it might have to do with the interaction between setRotation, setPartialWindow and setFullWindow. Just a wild guess...

**Comment by teo1978** [comment]
Turns out I was getting busy timeouts systematically on every **_Update_Full()** and **_Update_Part()**

Increasing the timeout time fixes it for me:
https://github.com/matteosistisette/GxEPD2_32/pull/1

**Comment by ZinggJM** [comment]
Thanks for the feedback. Now supported in GxEPD2_32_3C.
