### ISSUE TITLE
No suitable interface to "feed" a bitmap pixel-by-pixel into the screen

### ISSUE THREAD

**Issue by teo1978** [ZinggJM/GxEPD2_32#7]
The general workflow or paradigm provided by the classes in this library to deal with relatively large displays, and at the same time with controllers with small RAMs seems to be:

```c++
display.firstPage()
do {
  // Pretend you are drawing on the whole screen
  drawEverything();  
}
while (display.nextPage())
```

In reality, at each iteration, only the part of what you draw that is inside the current "page" is drawn to RAM,  while everything outside it is ignored. Then `nextPage()` sends the current page through the buffer and to the display, and so on. Very clever.

However, for drawing bitmaps that fit the whole screen in real-life applications, this workflow is mostly useless.

In order to draw a bitmap you do:
```c++
myDisplay.firstPage()
do {
  // Pretend you are drawing the whole bitmap on the whole screen
  display.drawInvertedBitmap(/*whatever*/);  
}
while (display.nextPage())
```

For large displays and small RAMs, that is only viable if you have the bitmap in the program memory, as a `const unsigned char[] PROGMEM` (as in the examples). In real life, that will never be the case.

If you want to draw a **bitmap** that is **read at runtime from some source** (e.g. downloaded from the Internet, or read from some storage media), you would need to copy the whole bitmap into the RAM before you can use `drawInvertedBitmap()`, and you usually wouldn't have enough RAM for that (which is why the `nextPage()` mechanism is there in the first place). Not to mention `drawInvertedBitmap()` expects the bitmap to be a _**const** whatever*_ (no idea why), so I'm not sure that could be done even if you had enough RAM.

So, in a scenario where you are **reading/loading/downloading/streaming** a whole-screen-size bitmap from some source that you want to draw on the screen, the obvious thing to do would be:
```c++
// pseudocode
unsigned char mybuffer[];
display.startWhatever();
while (not done) {
  int nbytes=getAFewBytesFromSomeSourceIntoTheBuffer(mybuffer);
  display.sendAFewPixels(mybuffer, nbytes);
}
display.endWhatever();
```

but there are currently no public methods in `GxEPD2_32_3C` that allow to do that.

Additionally, I can't even **write my own subclass of `GxEPD2_32_3C`** and add such methods, because all the useful "building blocks" are **private rather than protected**.

The only way you can currently accomplish downloading a bitmap (or getting it from some other source) in chunks, and feeding it into the screen, is by doing the following:
```c++
const int N=....;
unsigned char mybuffer[somesize]; //fits exactly N times in GxEPD2_32_3C's internal buffer
display.firstPage();
do {
  // - Figure out exactly what part of the bitmap the current page corresponds to, then:

  for (int i=0; i<N; i++) {
    /* We need to break this into smaller chunks because we likely don't have enough RAM 
       even for a buffer of the same size of GxEPD2_32_3C's one
       So: */
    
    int n=...; // - figure out what chunk to read/download from your source
    getNBytesFromSomeSourceIntoTheBuffer(n, mybuffer);
    for (int j=0; j<n; j++) {
      int x=....; // figure out the x and y of the pixel we are getting
      int y=....;
      unsigned char pixelcolor=mybuffer[j];
      display.drawPixel(x, y, pixelcolor);
    }
  }
}
while(display.nextPage())
```

I have done that and it actually works (mostly; there is some bug that messes with pixel colors in one particular row near the bottom of the screen, I think the first row of the last page); however, that is a **HORRIBLE MESS**.

There are **no public methods** to get the **x,y, width and height of the current page**, nor even the actual buffer size, so you have to know the actual buffer size and rely on that, and your code will break if the internal buffer size is changed. Not to mention how ridiculously intricate this is in the first place.

We **need an interface similar to that pictured in my third code snippet**. That actually wouldn't be much more than a few public wrappers around private methods that are already there.

**Comment by ZinggJM** [comment]
The goal of GxEPD2 is to keep it simple. If you want to change that, build your own mousetrap.
If you like the what exists in GxEPD or GxEPD2, just fork from it and change/extend what you like.
If you are good enough in this, users will switch to your version.

I need the time to work on my version, and I think of enhancements. But this is my hobby, no one can force me, and I close issues I don't like, be it its content or the form of the issue.

**Comment by teo1978** [comment]
> The goal of GxEPD2 is to keep it simple

The enhancement I suggest wouldn't complicate it. Indeed, it would make it even simpler.

> no one can force me

Yeah of course. I was just suggesting an enhancement.
I thought you would appreciate that it's a useful and necessary feature, and I'm sure you'd code it way better than I would, so I hoped you would be interested in implementing it. Unfortunately I was wrong.

> If you like the what exists in GxEPD or GxEPD2, just fork from it and change/extend what you like

Of course I will.

> If you are good enough in this, users will switch to your version.

The fact is I am definitely not good enough, and I wouldn't recomment anybody to switch to my version, because the only thing it will have better than yours will be this one feature, and it will be poorly coded. And also I'm not going to maintain my version, so as soon as you release your next version, mine will be shit except for this one feature.

That's why when I have made this enhancement I will issue a pull request, but then you'll reject it.

**Comment by ZinggJM** [comment]
There is no need to implement this in GxEPD2. The solution for this kind of usage exists already: the Waveshare demo libraries use a frame or line buffer in the application.
And for ESP8266 and ESP32 the Waveshare code is part of [https://github.com/Bodmer/TFT_eSPI](url)
