### ISSUE TITLE
Value of vcom dc should be changed or made configurable for GDEW075Z09

### ISSUE THREAD

**Issue by teo1978** [ZinggJM/GxEPD2_32#9]
On my Waveshare 7.5-inch b/w/r display, I was observing poor quality of red: red pixels would be pale and the shade of red wouldn't be consistent. For example, if you were to paint big red areas, they would not be homogeneous and you would observe evident "shadows" from images that had been previously displayed on the screen.

I contacted Waveshare tech support and they suggested me to change this:
```
_writeCommand(0X82);     //VDCS SETTING
_writeData(0x1E);        //decide by LUT file
```
to this:
```
_writeCommand(0X82);     //VDCS SETTING
_writeData(0x2E);        //decide by LUT file
```
I don't actually know what that does, but it does fix the issue completely for me.

I don't know whether:
A) that value is **just better** for this display (if so I wonder why their own demo code uses the other value), in which case it should be **changed** in the library, OR
B) it **might depend** on I-don't-know-what, so different values may be adequate for different usecases, in which case this should be made **configurable** in the library rather than hard-coded.

I am using an ESP8266 and the e-paper HAT from WaveShare.

**Comment by ZinggJM** [comment]
Please observe the issues template.

Post an example that shows the effect, then I can check on the 2 displays I have.

**Comment by teo1978** [comment]
I think the description is pretty clear and provides enough information. Up to you whether you want to work on it or not, of course.

The easiest way to observe the issue is:
- draw a few red, white and black vertical stripes and update the screen
- do the same with horizontal stripes

I don't have a ready-to-share example using your library, but I do have one with equivalent code that demonstrates the issue (most of the code is actually taken from the methods in your libraries and laid out in sequence).

To observe the issue:
- run the example (compiled with the Arduino IDE) once as-is
- comment out the "horizontal bands" section and uncomment the "vertical band" one, re-run
- or viceversa

You should observe the issue (i.e. the red stripes are not homogeneous but exhibit paler and darker sections that correspond to where different colors were in the previous image).

Then change the value sent after the "VDCS SETTING" command from 0x1E to 0x2E, test again, and you should see the issue is gone.

That's what I observe on my WaveShare display with an ESP8266.

```
#include <SPI.h>

const int EINK_CS = SS;
const int EINK_DC = 0;
const int EINK_RST = 2;
const int EINK_BUSY = 4;

const int WIDTH=640;
const int HEIGHT=384;


void setup() {
  Serial.begin(115200);

  pinMode(EINK_CS, OUTPUT);
  pinMode(EINK_RST, OUTPUT);
  pinMode(EINK_BUSY, INPUT);
  pinMode(EINK_DC, OUTPUT);

  // from https://github.com/ZinggJM/GxEPD2_32
  digitalWrite(EINK_CS, HIGH);
  digitalWrite(EINK_DC, HIGH);
  digitalWrite(EINK_RST, HIGH);
  delay(20);
  digitalWrite(EINK_RST, LOW);
  delay(20);
  digitalWrite(EINK_RST, HIGH);
  delay(200);

  initSPI();

  initDisplay();

  _writeCommand(0x04);
  _waitWhileBusy("_PowerOn");


  // -- Send pixel data to fill the whole screen ---

  _writeCommand(0x10);

  for (int i=0; i<640*384/2; i++) {

    /* 
    //Vertical bands
    if (i%160<40) {
      // two black pixels
      _writeData(0x00);
    }
    else if (i%160<80) {
      // two white pixels
      _writeData(0x33);
    }
    else {
      // two red pixels
      _writeData(0x44);
    }
    */
    
    
    // Horizontal bands
    if ((i/320)%80<20) {
      // two black pixels
      _writeData(0x00);
    }
    else if ((i/320)%80<40) {
      // two red pixels
      _writeData(0x44);
    }
    else {
      // two white pixels
      _writeData(0x33);
    }
    
    
    
  }

  // ----

  
  _writeCommand(0x12); //display refresh
  _waitWhileBusy("_Update_Full");
  delay(200);
  _writeCommand(0x02); // power off
  _waitWhileBusy("_PowerOff");
}

void loop() {
  
}

void initDisplay() {
  // From https://github.com/ZinggJM/GxEPD2_32

  // reset required for wakeup
  digitalWrite(EINK_RST, 0);
  delay(10);
  digitalWrite(EINK_RST, 1);
  delay(10);
  
  /**********************************release flash sleep**********************************/
      _writeCommand(0X65);     //FLASH CONTROL
      _writeData(0x01);
      _writeCommand(0xAB);
      _writeCommand(0X65);     //FLASH CONTROL
      _writeData(0x00);
      /**********************************release flash sleep**********************************/
      _writeCommand(0x01);
      _writeData (0x37);       //POWER SETTING
      _writeData (0x00);
      _writeCommand(0x04);     //POWER ON
      _waitWhileBusy("POWER");
      _writeCommand(0X00);     //PANNEL SETTING
      _writeData(0xCF);
      _writeData(0x08);
      _writeCommand(0x06);     //boost
      _writeData (0xc7);
      _writeData (0xcc);
      _writeData (0x28);
      _writeCommand(0x30);     //PLL setting
      _writeData (0x3c);
      _writeCommand(0X41);     //TEMPERATURE SETTING
      _writeData(0x00);
      _writeCommand(0X50);     //VCOM AND DATA INTERVAL SETTING
      _writeData(0x77);
      _writeCommand(0X60);     //TCON SETTING
      _writeData(0x22);
      _writeCommand(0x61);     //tres 640*384
      _writeData (0x02);       //source 640
      _writeData (0x80);
      _writeData (0x01);       //gate 384
      _writeData (0x80);
      _writeCommand(0X82);     //VDCS SETTING
      _writeData(0x1E);        //decide by LUT file
      _writeCommand(0xe5);     //FLASH MODE
      _writeData(0x03);


}

void initSPI() {
  SPI.begin();
  SPI.setDataMode(SPI_MODE0);
  SPI.setBitOrder(MSBFIRST);
#if defined(SPI_HAS_TRANSACTION)
  SPISettings settings(4000000, MSBFIRST, SPI_MODE0);
  SPI.beginTransaction(settings);
  SPI.endTransaction();
#else
  SPI.setFrequency(4000000);
#endif
}

void _waitWhileBusy(const char* comment)
{
  unsigned long start = micros();
  while (1)
  {
    if (digitalRead(EINK_BUSY) != LOW) break;
    delay(1);
    if (micros() - start > 40000000 )
    {
      Serial.println("Busy Timeout!");
      break;
    }
  }
  if (comment)
  {
#if !defined(DISABLE_DIAGNOSTIC_OUTPUT)
    unsigned long elapsed = micros() - start;
    Serial.print(comment);
    Serial.print(" : ");
    Serial.println(elapsed);
#endif
  }
  (void) start;
}

void _writeCommand(uint8_t c)
{
  digitalWrite(EINK_CS, LOW);
  digitalWrite(EINK_DC, LOW);
  SPI.transfer(c);
  digitalWrite(EINK_CS, HIGH);
  digitalWrite(EINK_DC, HIGH);
}

void _writeData(uint8_t d)
{
  digitalWrite(EINK_CS, LOW);
  SPI.transfer(d);
  digitalWrite(EINK_CS, HIGH);
}

void _writeData(const uint8_t* data, uint16_t n)
{
  digitalWrite(EINK_CS, LOW);
  for (uint8_t i = 0; i < n; i++)
  {
    SPI.transfer(*data++);
  }
  digitalWrite(EINK_CS, HIGH);
}
```

**Comment by ZinggJM** [comment]
Please show some respect. If you want me to do something for you, do your work first and prepare an example for my library. Otherwise I will just close and lock this issue.

**Comment by teo1978** [comment]
> Please show some respect

Could you tell me where you think I have shown any disrespect? So the next time I'll be more careful.

> If you want me to do something for you,

What? No, I'm not asking you to do anything for me at all. I am suggesting an improvement for your library.

I already found the solution I needed, I could have kept it for me but instead I came here to share it with you in case it could be useful for you and for other users. I'm [not] sorry if I didn't elaborate it more and only shared what I had. Actually I think that was precisely an act of respect, and of gratitude for this library that has been so useful to me, so every time I see an opportunity to give something back, as little and insignificant as it might be, I try to do so. But I guess I'll stop, as it seems to annoy you rather than anything.

> do your work first and prepare an example for my library
> Otherwise I will just close and lock this issue.

As  I said, that's up to you. Why you are not interested in looking into it is beyond me, but obviously it's your library and it's up to you.

Actually I really think you are the one who should show a bit more respect to somebody who has come here with the only intention to contribute. The contribution might be small, insignificant, or even totally useless, but that doesn't mean I deserve to be treated like that.

I came here to help, not to ask for help. Do whatever you want.
